import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const base = process.env.UI_BASE_URL ?? 'http://localhost:3115';
const browser = await chromium.launch({ args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(base);
  await page.getByRole('button', { name: 'Enable microphone & join' }).click();
  const sensor = page.getByRole('region', { name: 'SkyMesh sensor window' });
  await sensor.waitFor({ timeout: 60000 });
  await page.waitForTimeout(300);
  async function drag(handle, dx, dy) {
    const b = await handle.boundingBox();
    const x = b.x + Math.min(b.width / 2, 100), y = b.y + 20;
    await page.mouse.move(x, y); await page.mouse.down();
    await page.mouse.move(x + dx, y + dy, { steps: 12 }); await page.mouse.up();
  }
  let before = await sensor.boundingBox();
  await drag(sensor.locator('header').first(), 100, 50);
  let after = await sensor.boundingBox();
  assert(Math.abs(after.x - before.x - 100) < 2);
  assert(Math.abs(after.y - before.y - 50) < 2);
  const qr = page.getByRole('button', { name: 'Open skymesh-join.svg' });
  before = await qr.boundingBox(); await drag(qr, 160, 60); after = await qr.boundingBox();
  assert(Math.abs(after.x - before.x - 160) < 2);
  assert.equal(await page.getByRole('dialog').count(), 0, 'Dragging must not open QR');
  await qr.click();
  const dialog = page.getByRole('dialog'); await dialog.waitFor();
  assert(await dialog.evaluate(e => e.getAnimations().some(a => a.effect.getTiming().duration === 220)), 'Viewer must animate open');
  await page.waitForTimeout(260);
  before = await dialog.boundingBox(); await drag(dialog.locator('header'), 110, 40); after = await dialog.boundingBox();
  assert(Math.abs(after.x - before.x - 110) < 2);
  assert(Math.abs(after.y - before.y - 40) < 2);
  await page.getByRole('button', { name: 'Close QR image' }).click(); await dialog.waitFor({ state: 'hidden' });
  assert(await qr.evaluate(e => e === document.activeElement));
  const video = page.getByRole('button', { name: 'Open drone-demo.mp4', exact: true });
  before = await video.boundingBox(); await drag(video, 170, 80); after = await video.boundingBox();
  assert(Math.abs(after.x - before.x - 170) < 2);
  assert.equal(await dialog.count(), 0, 'Dragging must not open video');
  await video.click(); await dialog.waitFor();
  assert.equal(await dialog.locator('iframe').getAttribute('src'), 'https://www.youtube-nocookie.com/embed/DUTQkbuzxtk');
  await page.waitForTimeout(260);
  before = await dialog.boundingBox(); await drag(dialog.locator('header'), -90, -30); after = await dialog.boundingBox();
  assert(Math.abs(after.x - before.x + 90) < 2);
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' });
  assert.equal(await page.locator('iframe').count(), 0, 'Closing video unmounts player');
  await drag(qr, -1000, -1000); after = await qr.boundingBox();
  assert(after.x >= 0 && after.y >= 0, 'Icon constrained to desktop');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await qr.focus(); await page.keyboard.press('Enter'); await dialog.waitFor();
  assert.equal(await dialog.evaluate(e => e.getAnimations().length), 0);
  await page.keyboard.press('Escape'); await dialog.waitFor({ state: 'hidden' });
  await page.setViewportSize({ width: 390, height: 900 });
  await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth);
  await page.getByRole('button', { name: 'Close sensor and return to welcome' }).click();
  await page.getByRole('button', { name: 'Resume sensor', exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS: sensor moved 100x50, QR icon 160x60, QR viewer 110x40, video icon 170x80, video viewer -90x-30; drag never opens files; boundaries, 220ms animation, keyboard, reduced motion, resize and close all pass.');
} finally { await browser.close(); }
