import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const base = process.env.APP_URL ?? 'http://127.0.0.1:8128';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({viewport:{width:1440,height:900}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`${base}/station/?session=geo-${Date.now()}`);
  await page.waitForFunction(() => [...document.querySelectorAll('.leaflet-tile-loaded')].some(img => img.naturalWidth > 0),null,{timeout:15000});
  assert(await page.getByText('OpenStreetMap',{exact:true}).isVisible());
  assert(await page.getByText(/Illustrative map anchor/).isVisible());
  const overlay=page.locator('.geographic-room-overlay');
  const streetWidth=(await overlay.boundingBox()).width;
  await page.getByRole('button',{name:'Fit participant area',exact:true}).click();
  await page.waitForFunction(w => document.querySelector('.geographic-room-overlay').getBoundingClientRect().width > w * 2, streetWidth);
  await page.getByRole('button',{name:'Street overview',exact:true}).click();
  await page.waitForFunction(w => Math.abs(document.querySelector('.geographic-room-overlay').getBoundingClientRect().width-w)<2, streetWidth);
  const before=await overlay.boundingBox();
  const map=await page.locator('.geographic-map').boundingBox();
  await page.mouse.move(map.x+150,map.y+80);
  await page.mouse.down();await page.mouse.move(map.x+250,map.y+130,{steps:12});await page.mouse.up();
  await page.waitForTimeout(400);
  assert(Math.abs((await overlay.boundingBox()).x-before.x)>20,'map pans independently of room coordinates');
  await page.getByRole('button',{name:'Street overview',exact:true}).click();
  await page.waitForFunction(x => Math.abs(document.querySelector('.geographic-room-overlay').getBoundingClientRect().x-x)<2, before.x);
  await page.getByText('Set map anchor',{exact:true}).click();
  await page.getByLabel('Map anchor latitude',{exact:true}).fill('91');
  await page.getByRole('button',{name:'Apply map anchor',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Enter latitude'}).waitFor();
  await page.getByLabel('Map anchor latitude',{exact:true}).fill('40.7128');
  await page.getByLabel('Map anchor longitude',{exact:true}).fill('-74.006');
  await page.getByRole('button',{name:'Apply map anchor',exact:true}).click();
  await page.getByText(/Operator-set map anchor/).waitFor();
  assert.equal(await page.locator('[data-node-id]').count(),0,'changing map anchor does not create nodes');
  await page.reload();
  await page.getByText(/Operator-set map anchor/).waitFor();
  assert.equal(await page.getByLabel('Map anchor latitude',{exact:true}).inputValue(),'40.7128');
  await page.route('**/*.tile.openstreetmap.org/**',r=>r.abort());
  await page.reload();
  await page.getByRole('status').filter({hasText:'Basemap tiles unavailable'}).waitFor();
  await page.getByRole('button',{name:'Fit participant area',exact:true}).click();
  assert(await page.locator('.room-map svg').isVisible(),'live overlay survives tile failure');
  assert.deepEqual(errors,[]);
  console.log('PASS geographic basemap: real loaded tiles, attribution, focus/overview, pan/recenter, validated and persisted display anchor, no invented nodes, offline overlay fallback.');
} finally {await browser.close();}
